#!/usr/bin/python3
#+
# This script allows for convenient viewing of any particular
# page of the Android API reference. Invoke it as follows:
#
#      android-ref class-or-pkg-name
#
# and it will launch your preferred Web browser to view the
# documentation for the specified fully-qualified class or
# package name.
#
# Written by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
#-

import sys
import webbrowser

if len(sys.argv) != 2 :
    raise RuntimeError("expecting exactly one arg, the fully-qualified class or package name")
#end if

path = sys.argv[1].split(".")
is_class = path[-1][0].isupper()
webbrowser.open_new \
  (
        "http://developer.android.com/reference/%(path)s%(suffix)s.html"
    %
        {
            "path" : "/".join(path),
            "suffix" : ("/package-summary", "")[is_class],
        }
  )
