#!/usr/bin/python3
#+
# This script allows for convenient viewing of any particular
# page of the API reference for Android, Python 2 or Python 3.
# Invoke it as follows:
#
#      viewref api [class-or-pkg-name]
#
# where api is "android", "python2" or "python3", and it will launch
# your preferred Web browser to view the documentation for the
# specified fully-qualified class or package name in the specified
# API. If class-or-pkg-name is omitted, the overall API summary
# page is displayed.
#
# Examples:
#
#     viewref android android.content.Intent
#     viewref android java.lang
#     viewref android
#     viewref python2 os.path
#     viewref python3 subprocess
#
# Written by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
#-

import sys
import re
import webbrowser

def fixpath_android(pathstr) :
    "fixes up URL paths for classes declared within classes.\n" \
    "These are recognized because their parent has a name beginning with\n" \
    "an uppercase letter. Note this code only goes one level deep."
    parent_uc = re.search(r"\/[A-Z]\w+(\/)([A-Za-z]\w+)$", pathstr)
    if parent_uc != None :
        # change last "/" to "."
        pathstr = pathstr[:parent_uc.start(1)] + "." + parent_uc.group(2)
    #end if
    return \
        pathstr
#end fixpath_android

apis = \
    {
        "android" :
            {
                "urlfmt" : "http://developer.android.com/reference/%(path)s%(suffix)s.html",
                "pathsep" : "/",
                "fixpath" : fixpath_android,
                "suffixfn" : lambda path : ("packages", ("/package-summary", "")[len(path) > 0 and (path[-1][0].isupper() or len(path) > 1 and path[-2][0].isupper())])[len(path) != 0],
            },
        "python2" :
            {
                "urlfmt" : "http://docs.python.org/library/%(path)s%(suffix)s",
                "pathsep" : ".",
                "suffixfn" : lambda path : ("", ".html")[len(path) != 0],
            },
        "python3" :
            {
                "urlfmt" : "http://docs.python.org/3/library/%(path)s%(suffix)s",
                "pathsep" : ".",
                "suffixfn" : lambda path : ("", ".html")[len(path) != 0],
            },
    }

if len(sys.argv) not in (2, 3) :
    raise RuntimeError("expecting exactly one or two args, the API and the fully-qualified class or package name")
#end if

api_name = sys.argv[1]
if not api_name in apis :
    raise RuntimeError("unrecognized API %s" % api_name)
#end if
api = apis[api_name]
if len(sys.argv) > 2 :
    path = sys.argv[2].split(".")
else :
    path = ()
#end if
pathstr = api["pathsep"].join(path)
fixpath = api.get("fixpath")
if fixpath != None :
    pathstr = fixpath(pathstr)
#end if
webbrowser.open_new \
  (
        api["urlfmt"]
    %
        {
            "path" : pathstr,
            "suffix" : api.get("suffixfn", lambda path : "")(path),
        }
  )
